config/routes.rb
Rails.application.routes.draw do
  
  get "/shop", to: "payments#shop"
  get "payments/express"
  get "transactions/checkout"
  resources :categories
  resources :payments
  get 'contact/index'
  
  resources :pictures
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :comments
  resources :apartments do
    resources :comments
  end
  devise_for :users, controllers:{registrations: "registrations"}
  resources :users, only: [:show, :index]

  get "/dashboard", to: "welcome#dashboard"
  get "/MisPropiedades", to: "welcome#ownerDashboard"
  put "apartments/:id/ownerUnRent", to: "apartments#ownerUnRent"
  put "apartments/:id/adminPublish", to: "apartments#adminPublish"
  put "apartments/:id/adminUnPublish", to: "apartments#adminUnPublish"

  root 'welcome#index'

end

app/views/partials/_navigation.html.erb
 
<!--Barra superior -->
 <div class="row transparent-menu-top">
    <div class="container clear-padding">
      <div class="navbar-contact">
        <div class="col-md-7 col-sm-6 clear-padding">
          <a href="/contact/index" class="transition-effect"><i class="fa fa-phone"></i> (+56) 9 67698322</a>
          <a href="/contact/index" class="transition-effect"><i class="fa fa-envelope-o"></i> contacto@laserenafun.cl</a>
        </div>
        <div class="col-md-5 col-sm-6 clear-padding search-box">
          <div class="col-md-6 col-xs-5 clear-padding">
            
          </div>
<div class="col-md-6 col-xs-7 clear-padding user-logged">
  <%if user_signed_in?%>
      <%=link_to current_user.name, edit_user_registration_path(current_user)%> <i class="fa fa-user" style="color:white"></i>      
      <%= link_to "Cerrar Sessión",destroy_user_session_path,method: :delete %> <i class="fa fa-sign-out" style="color:white"></i>
  <%else%>
      <%= link_to "Ingresar", new_user_session_path %> <i class="fa fa-sign-in" style="color:white"></i>

      <%= link_to "Registrarse", new_user_registration_path %> <i class="fa fa-user-plus" style="color:white"></i>

  <%end%>
</div>
  
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
<!--Fin Barra Superior -->


<!-- -->
<div class="row transparent-menu">
        <div class="container clear-padding">
            <!-- BEGIN: HEADER -->
            <div class="navbar-wrapper">
                <div class="navbar navbar-default" role="navigation">
                    <!-- BEGIN: NAV-CONTAINER -->
                    <div class="nav-container">
                        <div class="navbar-header">
                            <!-- BEGIN: TOGGLE BUTTON (RESPONSIVE)-->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            
                            <!-- BEGIN: LOGO -->
                            <%= link_to "La Serena Fun", root_path, :class => "navbar-brand logo" %>
                        </div>
                        
                        <!-- BEGIN: NAVIGATION -->       
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav navbar-right">
                             <%if can? :create, Apartment %>
                                <li class="dropdown ">
                                <a href="lko" class="dropdown-toggle " data-toggle="dropdown" target="_blank">Propiedades<b class="caret"></b></a>
                                <ul class="dropdown-menu" role="menu">
                                <li><%=link_to "Mis Propiedades", "/MisPropiedades" %></li>
                        <li><%= link_to "Publicar Nueva Propiedad", new_apartment_path,class:" button "%></li>
                                </ul>
                                </li>
                              <%end%>
                              <li class="dropdown ">
                                <a href="lko" class="dropdown-toggle " data-toggle="dropdown" target="_blank">Arriendos<b class="caret"></b></a>
                                <ul class="dropdown-menu" role="menu">
                                <li><%= link_to 'Todos', apartments_path%></li>
                                <% @categories.each do |category|%>
                                <li><%=link_to category.name, category%></li>
                               <%end%>
                                </ul>
                                </li>
                                <li><a href="/contact/index">Contacto</a></li>
                                <% if can? :access, :rails_admin %>
                                <li class="dropdown ">
                                <a href="lko" class="dropdown-toggle " data-toggle="dropdown" target="_blank">Administrar<b class="caret"></b></a>
                                <ul class="dropdown-menu" role="menu">
                                <li><%=link_to "Propiedades", dashboard_path %></li>
                                <li><%=link_to "Categorias", categories_path %></li>
                                <li><%= link_to 'Usuarios', users_path %></li>
                                <li><%= link_to 'Base de Datos', rails_admin_path %></li>
                                </ul>
                                </li>
                                <%end%>
                            </ul>
                        </div>
                        <!-- END: NAVIGATION -->
                    </div>
                    <!--END: NAV-CONTAINER -->
                </div>
            </div>
            <!-- END: HEADER -->
        </div>
<!-- -->
       
       </div>