config/routes.rb
Rails.application.routes.draw do
  
  get "/shop", to: "payments#shop"
  get "payments/express"
  get "transactions/checkout"
  resources :categories
  resources :payments
  get 'contact/index'
  
  resources :pictures
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :comments
  resources :apartments do
    resources :comments
  end
  devise_for :users, controllers:{registrations: "registrations"}
  resources :users, only: [:show, :index]

  get "/dashboard", to: "welcome#dashboard"
  get "/MisPropiedades", to: "welcome#ownerDashboard"
  put "apartments/:id/ownerUnRent", to: "apartments#ownerUnRent"
  put "apartments/:id/adminPublish", to: "apartments#adminPublish"
  put "apartments/:id/adminUnPublish", to: "apartments#adminUnPublish"

  root 'welcome#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
   belongs_to :apartment
   has_attached_file :image
  # Validate content type
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  # Validate filename
  validates_attachment_file_name :image, matches: [/png\Z/, /jpe?g\Z/]
  # Explicitly do not validate
  do_not_validate_attachment_file_type :image
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Foto cargada exitosamente.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Foto actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    redirect_to(:back)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :description, :image, :cover, :apartment_id)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture, :html => {multipart: true}) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :cover %><br>
    <%= f.number_field :cover %>
  </div>
  <div class="form-group">
      <%= f.label :apartment_id, "Departamento" %><br>
      <%= f.collection_select :apartment_id,Apartment.all.where(user_id: current_user.id), :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th>Cover</th>
      <th>Apartment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= picture.description %></td>
        <td><%= picture.image %></td>
        <td><%= picture.cover %></td>
        <td><%= picture.apartment %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @picture.image %>
</p>

<p>
  <strong>Cover:</strong>
  <%= @picture.cover %>
</p>

<p>
  <strong>Apartment:</strong>
  <%= @picture.apartment %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>