config/routes.rb
Rails.application.routes.draw do
  
  get "/shop", to: "payments#shop"
  get "payments/express"
  get "transactions/checkout"
  resources :categories
  resources :payments
  get 'contact/index'
  
  resources :pictures
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :comments
  resources :apartments do
    resources :comments
  end
  devise_for :users, controllers:{registrations: "registrations"}
  resources :users, only: [:show, :index]

  get "/dashboard", to: "welcome#dashboard"
  get "/MisPropiedades", to: "welcome#ownerDashboard"
  put "apartments/:id/ownerUnRent", to: "apartments#ownerUnRent"
  put "apartments/:id/adminPublish", to: "apartments#adminPublish"
  put "apartments/:id/adminUnPublish", to: "apartments#adminUnPublish"

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true
	has_many :apartments

	before_destroy :chequear_por_propiedades

	private

	  def chequear_por_propiedades
	    if apartments.any?
	    	return false
	    end
	  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Categoria creada exitosamente.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy

    if @category.destroyed?

      respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoria eliminada.' }
      format.json { head :no_content }
      end
    else
        respond_to do |format|
        format.html { redirect_to categories_url, notice: 'La categoria no se puede elimminar, exiten propiedades que aun pertenecen a esta categoria. Por favor cambie la categoria de estas propiedades. ' }
        format.json { head :no_content }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name,"Nombre" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Publicar", :class => 'btn btn-success' %>
  </div>
<% end %>

<style>
input[type="text"], input[type="password"],input[type="number"],textarea,select{
    width: 100%;
    height: auto;
    padding: 20px 0px;
    background: transparent;
    border: 0;
    border-bottom: 1px solid #435160;
    outline: none;
    color: #6D7781;
    font-size: 16px;
}
</style>

app/views/categories/edit.html.erb
<div class="container well formborderCategory">
	<div class="row">
		<div class="form_title">
			<h1>Editar Categoría</h1>
		</div>


<%= render 'form' %>

<%= link_to 'Volver', categories_path %>
</div>
</div>

app/views/categories/index.html.erb
<div class="container well formborderCategory">
  <div class="row">
  <div class="form_title">
    <h1>Categorías</h1>
  </div>
    <div class="col-md-9 center-block no-float">

<%unless @categories.empty?%>
<table>
  <thead>
    <tr>
      <th>NOMBRE</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<%end%>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><h3><%= category.name %></h3></td>
        <td><%= link_to 'EDITAR', edit_category_path(category),class:"btn btn-warning" %></td>
        <td><%= link_to 'ELIMINAR', category, method: :delete, data: { confirm: '¿Estas seguro?' },class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Categoría', new_category_path, class:"btn btn-success" %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container well formborderCategory">
	<div class="row">
		<div class="form_title">
			<h1>Nueva Categoría</h1>
		</div>
		<div class="col-md-9 center-block no-float">
		<%= render 'form' %>
		<%= link_to 'Volver', categories_path %>
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<div class="row page-title">
        <div class="container clear-padding text-center flight-title">
            <h3>Propiedades</h3>
            <h4 class="thank">Explora L@s <%= @category.name %> Disponibles</h4>
        </div>
    </div>
    <!-- END: PAGE TITLE -->
<!-- START: LISTING AREA-->
<div class="row">
    <div class="container clear-padding">
        <!-- START: INDIVIDUAL LISTING AREA -->
        <div class="hotel-listing text-center">
            <!-- START: HOTEL GRID VIEW -->
            <%= render @category.apartments.publicados_sinArrrendar.ultimos %>
            <div class="clearfix"></div>
            <!-- END: HOTEL GRID VIEW -->
            <!-- START: PAGINATION -->
            <!-- END: PAGINATION -->
        </div>
        <!-- END: INDIVIDUAL LISTING AREA -->
    </div>
</div>

</div>
</div>